export const GET_MOVIES="GET_MOVIES";
export const GET_MOVIES_SUCCESS="GET_MOVIES_SUCCESS";
export const GET_MOIVE_BY_TITLE="GET_MOVIE_BY_TITLE";
export const GET_MOIVE_BY_TITLE_SUCCESS="GET_MOVIE_BY_TITLE_SUCCESS";