export const GET_STOCK="GET_STOCK";
export const GET_STOCK_SUCCESS="GET_STOCK_SUCCESS";
export const GET_STOCK_BY_DATE="GET_STOCK_BY_DATE";
export const GET_STOCK_BY_DATE_SUCCESS="GET_STOCK_BY_DATE_SUCCESS";